version: '2'
services:
  load_balancer:
    build: ./load_balancer
    container_name: load_balancer
    ports:
      - "8080:80"
    links:
      - web_1:web_1
      - web_2:web_2
  web_1:
    build: ./web
    hostname: web_1
    container_name: web_1
    links:
      - db
  web_2:
    build: ./web
    hostname: web_2
    container_name: web_2
    links:
      - db
  db:
    build: ./db
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=s3cr3t
      - MYSQL_USER=web_user
      - MYSQL_PASSWORD=s3cr3t
