version: '3'
services:
  load_balancer:
    build: ./load_balancer
    container_name: load_balancer
    ports:
      - "8080:80"
    links:
      - "web_1"
      - "web_2"
    volumes:
      - ./load_balancer/conf:/etc/nginx/conf.d
  web_1:
    build: ./web
    container_name: web_1
    volumes:
      - ./web/conf:/etc/nginx/conf.d
      - ./web_app:/var/www/html
    links:
      - "db"
  web_2:
    build: ./web
    container_name: web_2
    volumes:
      - ./web/conf:/etc/nginx/conf.d
      - ./web_app:/var/www/html
    links:
      - "db"
  db:
    build: ./db
    container_name: db
