---
- name: install mariadb
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - mariadb
    - mariadb-server

- name: install mariadb python for security
  yum: name=MySQL-python state=present

- name: start mariadb
  service: name=mariadb state=started enabled=yes

- name: set db user
  mysql_user: name={{ db_user }} password={{ db_pwd }} priv=*.*:ALL host='%' state=present

- name: open 3306 port
  firewalld:
    port: 3306/tcp
    permanent: true
    immediate: true
    state: enabled
    zone: public

- name: enable mariadb to firewall
  firewalld:
    service: mariadb
    immediate: true
    permanent: true
    state: enabled
    zone: public

- name: disable SELinux
  selinux:
    state: disabled