---
- hosts: webservers
  become: true
  gather_facts: no

  tasks:
    - name: install apache httpd, php, php-mysql
      yum: name={{item}} state=present update_cache=yes
      with_items:
        - httpd
        - php
        - php-mysql

    - name: start apache2
      service: name=apache2 state=started enabled=yes
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

