---
- hosts: all
  become: true
  remote_user: root
  gather_facts: no
  roles:
    - common

- hosts: webservers
  become: true
  roles:
    - web

- hosts: databases
  become: true
  roles:
    - db
