# Playbook from https://github.com/veggiemonk/ansible-ohmyzsh/blob/master/tasks/main.yml
# with few additions
---
- name: security question
  expect:
    command: echo "you god damn right!"
    responses:
      'say my name? (lowercase)': "heisenberg"
    echo: yes

- name: Installing Zsh and git
  yum: pkg=zsh,git state=latest
  register: installation

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
  when: installation|success
  become: no

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  become: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning|success
  become: no
