# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

project = "vagrant-ansible-configuration-management"
box_name = "Novitoll/centos7"

Vagrant.configure(VAGRANT_API_VERSION) do |config|

  config.vm.define "web" do |web|
    web.vm.box = box_name
    web.vm.network "private_network", ip: "192.168.56.102"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.hostname = "web"
  end

  config.vm.define "db" do |db|
    db.vm.box = box_name
    db.vm.network "private_network", ip: "192.168.56.103"
    db.vm.network "forwarded_port", guest: 3306, host: 3307
    db.vm.hostname = "db"
  end

  config.vm.define "ansible", primary: true do |ansible|
    ansible.vm.box = box_name
    ansible.vm.network "private_network", ip: "192.168.56.101"
    ansible.vm.hostname = "ansible"
    ansible.vm.provision "shell", path: "./bootstrap-ansible.sh"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
  end

  config.vm.synced_folder "..", "/vagrant", disabled: true

end