---
AWSTemplateFormatVersion: '2010-09-09'
Description: Main template to build stacks all together

Parameters:
  # 1. networking params
  NetworkingURL:
    Type: String
    Description: URL for the networking template
    Default: https://s3.amazonaws.com/cf-templates-9ybl3rilvq15-us-east-1/networking.yml
  CIDRRange:
    Description: VPCCIDR Range (will be a /16 block)
    Type: String
    Default: 10.251.0.0
    AllowedValues: [10.250.0.0, 10.251.0.0]

  # 2. security params
  SecurityGroupsURL:
    Type: String
    Description: URL for the networking template
    Default: https://s3.amazonaws.com/cf-templates-9ybl3rilvq15-us-east-1/security_groups.yml

  # 3. database params
  DatabaseURL:
    Type: String
    Description: URL for the networking template
    Default: https://s3.amazonaws.com/cf-templates-9ybl3rilvq15-us-east-1/db.yml
  DBInstanceClass:
    Type: String
    Description: Architecture of RDS instance
    Default: db.t2.micro
    AllowedValues: [db.t2.micro, db.t2.small]
  DBName:
    Type: String
    Description: Name of the DB instance
  DBUser:
    NoEcho: true
    Type: String
    Description: Name of the DB instance user (Min 8 [a-zA-Z0-9] characters)
    AllowedPattern: "^[a-zA-Z0-9]*$"
    MinLength: 2
    MaxLength: 64
  DBPassword:
    NoEcho: true
    Type: String
    Description: Password for the DB instance user (Min 8 [a-zA-Z0-9] characters)
    AllowedPattern: "^[a-zA-Z0-9]*$"
    MinLength: 8
    MaxLength: 19
  DBSlowQueryLog:
    Type: String
    Description: To create the slow query log, set to 1. The default is 0.
    Default: 0
    AllowedValues: [0, 1]

  # 4. web params
  WebURL:
    Type: String
    Description: URL for the networking template
    Default: https://s3.amazonaws.com/cf-templates-9ybl3rilvq15-us-east-1/web.yml
  InstanceType:
    Type: String
    Description: EC2 instance type
    AllowedValues: ["t1.micro", "t2.nano", "t2.micro", "t2.small", "t2.medium", "t2.large", "m1.small", "m1.medium", "m1.large", "m1.xlarge", "m2.xlarge", "m2.2xlarge", "m2.4xlarge", "m3.medium", "m3.large", "m3.xlarge", "m3.2xlarge", "m4.large", "m4.xlarge", "m4.2xlarge", "m4.4xlarge", "m4.10xlarge", "c1.medium"]
    Default: t2.micro
  ASGInstanceCount:
    Type: Number
    MaxValue: 2
    MinValue: 1
    Description: Number of EC2 instances to scale in ASG (max. 2)
  SSHKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH KeyPair name


Resources:
  Networking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref NetworkingURL
      Parameters:
        CIDRRange: !Ref CIDRRange
      Tags:
        - Key: Name
          Value: !Join ["", [!Ref 'AWS::StackName', '-Networking']]

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupsURL
      Parameters:
        VPCId: !GetAtt [Networking, "Outputs.VPCID"]
      Tags:
        - Key: Name
          Value: !Join ["", [!Ref 'AWS::StackName', '-SecurityGroups']]

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref DatabaseURL
      Parameters:
        PrivateSubnets: !Join [",", [!GetAtt [Networking, "Outputs.SubnetPrivateAZ1"],
                                     !GetAtt [Networking, "Outputs.SubnetPrivateAZ2"]]]
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBName
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        DBSlowQueryLog: !Ref DBSlowQueryLog
        SecurityGroups: !Join [",", [!GetAtt [SecurityGroups, "Outputs.AdminSGId"],
                                     !GetAtt [SecurityGroups, "Outputs.RDS4EC2SGId"]]]
      Tags:
        - Key: Name
          Value: !Join ["", [!Ref 'AWS::StackName', '-Database']]

  Web:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref WebURL
      Parameters:
        VPCId: !GetAtt [Networking, "Outputs.VPCID"]
        PublicSubnets: !Join [",", [!GetAtt [Networking, "Outputs.SubnetPublicAZ1"],
                                     !GetAtt [Networking, "Outputs.SubnetPublicAZ2"]]]
        PrivateSubnets: !Join [",", [!GetAtt [Networking, "Outputs.SubnetPrivateAZ1"],
                                     !GetAtt [Networking, "Outputs.SubnetPrivateAZ2"]]]
        PrivateSecurityGroups: !Join [",", [!GetAtt [SecurityGroups, "Outputs.AdminSGId"],
                                            !GetAtt [SecurityGroups, "Outputs.EC2SGId"]]]
        PublicSecurityGroups: !Join [",", [!GetAtt [SecurityGroups, "Outputs.AdminSGId"],
                                           !GetAtt [SecurityGroups, "Outputs.ELBSGId"]]]
        InstanceType: !Ref InstanceType
        ASGInstanceCount: !Ref ASGInstanceCount
        SSHKeyPairName: !Ref SSHKeyPairName
        RDSEndpoint: !GetAtt [Database, "Outputs.RDSEndpoint"]
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
      Tags:
        - Key: Name
          Value: !Join ["", [!Ref 'AWS::StackName', '-Web']]

Outputs:
  URL:
    Value: !GetAtt [Web, "Outputs.WebsiteURL"]


