# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

project = "vagrant"
shared_dir = "/custom_shared"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "Novitoll/centos7"
  config.vm.network "forwarded_port", guest: 80, host: 9999
  config.vm.hostname = "single"

  # use "../Vagrant" directory as the project
  config.vm.synced_folder "..", "#{shared_dir}"
  config.vm.synced_folder "..", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
  end

  config.vm.provision "shell", path: "../lamp-provision.sh", args: "#{shared_dir}"

end