# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

project = "vagrant"
shared_dir = "/custom_shared"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "Novitoll/centos7"
  config.vm.network "public_network", ip: "192.168.56.102"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.hostname = "single"

  # use project's root directory
  config.vm.synced_folder "../..", "#{shared_dir}"
  config.vm.synced_folder "../..", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
  end

  config.vm.provision "shell", path: "../lamp-provision.sh", args: "#{shared_dir}",
    env: {
          "DB_USER": "root",
          "DB_PWD": "s3cr3t"
    }

end