# -*- mode: ruby -*-
# vi: set ft=ruby :

project = "vagrant"

VAGRANT_API_VERSION = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "Novitoll/centos7"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.hostname = "single"

  # use "../Vagrant" directory as the project
  config.vm.synced_folder "..", "/custom_shared"
  config.vm.synced_folder "..", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
  end

  config.vm.provision "shell", path: "../lamp-provision.sh"
end